### ISSUE TITLE
NFTs not shown on My NFTs

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#162]
From AZero Punk:
I'm unable to list any NFTs, because they don't show up under My NFTs. Probably because I have all 10k of the NFTs in my account. Can you limit the collection to 100? Just for testing right now.

**Comment by langdon0003** [comment]
Still have no idea why it have only 20 items instead of 10K.
<img width="248" alt="image" src="https://user-images.githubusercontent.com/35419213/218083056-852105ce-631e-4966-ad85-7e0333e1ce24.png">


Current 20 NFTs load fine atm.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/35419213/218082681-e22236b9-ea6a-4d9a-a90e-e376c6d6cb6b.png">
