### ISSUE TITLE
User request: All Collections page

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#350]
Hi guys! I think the artzero marketplace should be much more accessible. I’ve shared it with a few friends and they all say it’s very hard to view all the collections on the market place. You always just get a few showing up under each category and people think there’s only a few projects live. 

There should be a default home page on the marketplace that lists all of the projects ie ‘all collections’ option.

Need a searchable/filterable all collections page, like stat.

Also, on a collection page, when you sort by "highest first" it shows lowest first and when you sort by "lowest first" it shows highest first.

**Comment by langdon0003** [comment]
- "Also, on a collection page, when you sort by "highest first" it shows lowest first and when you sort by "lowest first" it shows highest first."
=> This issue is fixed.

- New All collection page 
=>Need discuss with designer.
Currently we already have all collection with pagination at last section of Homepage.
![image](https://user-images.githubusercontent.com/35419213/233979846-ed751870-7d49-4be6-8578-13cb9f672a8e.png)

**Comment by langdon0003** [comment]
@mitchdoan please need further discuss

**Comment by mitchdoan** [comment]
UI to be revamped
